"use strict";(self.webpackChunkantd_one=self.webpackChunkantd_one||[]).push([[433],{95879:function(Y,h,n){n.r(h);var O=n(46686),a=n.n(O),l=n(50959),b=n(4273),v=n(26016),t=n(30990),s=n(85047),u=n(80163),B=n(48478),e=n(11527);h.default=function(){var y=(0,l.useState)("horizontal"),j=a()(y,2),o=j[0],G=j[1],T=(0,l.useState)("small"),S=a()(T,2),r=S[0],f=S[1],A=(0,l.useState)(9),D=a()(A,2),_=D[0],R=D[1],L=(0,l.useState)(7),P=a()(L,2),m=P[0],z=P[1],F=(0,l.useState)(17),E=a()(F,2),i=E[0],K=E[1],U=(0,l.useState)(0),Z=a()(U,2),d=Z[0],W=Z[1],w=(0,l.useState)(),I=a()(w,2),c=I[0],H=I[1],V=(0,l.useState)(8),g=a()(V,2),p=g[0],J=g[1],N=(0,l.useState)(4),M=a()(N,2),C=M[0],Q=M[1];return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)(b.Z,{gutter:100,children:[(0,e.jsx)(v.Z,{span:12,children:(0,e.jsxs)(t.Z,{size:"small",children:[(0,e.jsx)(t.Z.Item,{label:"layout",children:(0,e.jsxs)(s.ZP.Group,{value:o,onChange:function(x){return G(x.target.value)},children:[(0,e.jsx)(s.ZP.Button,{value:"horizontal",children:"Horizontal"}),(0,e.jsx)(s.ZP.Button,{value:"vertical",children:"Vertical"}),(0,e.jsx)(s.ZP.Button,{value:"inline",children:"Inline"})]})}),(0,e.jsx)(t.Z.Item,{label:"size",children:(0,e.jsxs)(s.ZP.Group,{value:r,onChange:function(x){return f(x.target.value)},children:[(0,e.jsx)(s.ZP.Button,{value:"large",children:"large"}),(0,e.jsx)(s.ZP.Button,{value:"default",children:"default"}),(0,e.jsx)(s.ZP.Button,{value:"small",children:"small"})]})}),(0,e.jsx)(t.Z.Item,{label:"\u7F51\u683C\u5E03\u5C40\u5217\u95F4\u8DDD",children:(0,e.jsx)(u.Z,{min:1,max:10,step:1,onChange:R,value:_})}),(0,e.jsx)(t.Z.Item,{label:"labelCol",children:(0,e.jsx)(u.Z,{min:1,max:24,step:1,onChange:z,value:m})}),(0,e.jsx)(t.Z.Item,{label:"\u5F39\u6027\u95F4\u8DDD",children:(0,e.jsx)(u.Z,{min:1,max:24,step:1,onChange:K,value:i})})]})}),(0,e.jsx)(v.Z,{span:12,children:(0,e.jsxs)(t.Z,{size:"small",children:[(0,e.jsx)(t.Z.Item,{label:"\u6700\u5C0F\u5217\u6570",children:(0,e.jsx)(u.Z,{min:1,max:10,step:1,onChange:W,value:d})}),(0,e.jsx)(t.Z.Item,{label:"\u6700\u5927\u5217\u6570",children:(0,e.jsx)(u.Z,{min:1,max:10,step:1,onChange:H,value:c})}),(0,e.jsx)(t.Z.Item,{label:"\u5217\u95F4\u8DDD",children:(0,e.jsx)(u.Z,{min:1,max:10,step:1,onChange:J,value:p})}),(0,e.jsx)(t.Z.Item,{label:"\u884C\u95F4\u8DDD",children:(0,e.jsx)(u.Z,{min:1,max:10,step:1,onChange:Q,value:C})})]})})]}),(0,e.jsx)("div",{style:{borderTop:"1px solid rgba(0,0,0,.1)",width:"100%",margin:"20px 0"}}),(0,e.jsx)(B.FormRender,{gridProps:{minColumns:d,maxColumns:c,columnGap:p,rowGap:C},layoutProps:{layout:o,size:r,gridColumnGap:_,labelCol:m,wrapperCol:i},fields:[{type:"Input",name:"Input",title:"Input"},{type:"Select",name:"Select",title:"Select2"},{type:"Input",name:"Input2",title:"Input"},{type:"Select",name:"Select2",title:"Select2"}]}),(0,e.jsx)("code",{children:(0,e.jsx)("pre",{children:`<FormRender
   layoutProps={{
      layout: `.concat(o,`,
      size: `).concat(r,`,
      gridColumnGap:`).concat(_,`,
      labelCol:`).concat(m,`,
      wrapperCol:`).concat(i,`,
    }}
    gridProps={{
      minColumns:`).concat(d,`,
      maxColumns:`).concat(c,`,
      columnGap:`).concat(p,`,
      rowGap:`).concat(C,`,
   }}
    fields={[...]}
   />`)})})]})}}}]);
