"use strict";(self.webpackChunkantd_one=self.webpackChunkantd_one||[]).push([[433],{80727:function(B,r,n){n.r(r);var v=n(46686),a=n.n(v),t=n(50959),S=n(4273),o=n(26016),l=n(30990),u=n(85047),s=n(80163),R=n(14550),e=n(11527);r.default=function(){var f=(0,t.useState)("horizontal"),E=a()(f,2),_=E[0],A=E[1],F=(0,t.useState)("small"),P=a()(F,2),m=P[0],T=P[1],b=(0,t.useState)(9),D=a()(b,2),i=D[0],G=D[1],L=(0,t.useState)(7),I=a()(L,2),d=I[0],K=I[1],U=(0,t.useState)(17),Z=a()(U,2),c=Z[0],W=Z[1],z=(0,t.useState)(0),g=a()(z,2),p=g[0],H=g[1],V=(0,t.useState)(),M=a()(V,2),x=M[0],w=M[1],J=(0,t.useState)(8),O=a()(J,2),h=O[0],N=O[1],Q=(0,t.useState)(4),y=a()(Q,2),C=y[0],X=y[1];return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)(S.Z,{gutter:100,children:[(0,e.jsx)(o.Z,{span:12,children:(0,e.jsxs)(l.Z,{size:"small",children:[(0,e.jsx)(l.Z.Item,{label:"layout",children:(0,e.jsxs)(u.ZP.Group,{value:_,onChange:function(j){return A(j.target.value)},children:[(0,e.jsx)(u.ZP.Button,{value:"horizontal",children:"Horizontal"}),(0,e.jsx)(u.ZP.Button,{value:"vertical",children:"Vertical"}),(0,e.jsx)(u.ZP.Button,{value:"inline",children:"Inline"})]})}),(0,e.jsx)(l.Z.Item,{label:"size",children:(0,e.jsxs)(u.ZP.Group,{value:m,onChange:function(j){return T(j.target.value)},children:[(0,e.jsx)(u.ZP.Button,{value:"large",children:"large"}),(0,e.jsx)(u.ZP.Button,{value:"default",children:"default"}),(0,e.jsx)(u.ZP.Button,{value:"small",children:"small"})]})}),(0,e.jsx)(l.Z.Item,{label:"\u7F51\u683C\u5E03\u5C40\u5217\u95F4\u8DDD",children:(0,e.jsx)(s.Z,{min:1,max:10,step:1,onChange:G,value:i})}),(0,e.jsx)(l.Z.Item,{label:"labelCol",children:(0,e.jsx)(s.Z,{min:1,max:24,step:1,onChange:K,value:d})}),(0,e.jsx)(l.Z.Item,{label:"\u5F39\u6027\u95F4\u8DDD",children:(0,e.jsx)(s.Z,{min:1,max:24,step:1,onChange:W,value:c})})]})}),(0,e.jsx)(o.Z,{span:12,children:(0,e.jsxs)(l.Z,{size:"small",children:[(0,e.jsx)(l.Z.Item,{label:"\u6700\u5C0F\u5217\u6570",children:(0,e.jsx)(s.Z,{min:1,max:10,step:1,onChange:H,value:p})}),(0,e.jsx)(l.Z.Item,{label:"\u6700\u5927\u5217\u6570",children:(0,e.jsx)(s.Z,{min:1,max:10,step:1,onChange:w,value:x})}),(0,e.jsx)(l.Z.Item,{label:"\u5217\u95F4\u8DDD",children:(0,e.jsx)(s.Z,{min:1,max:10,step:1,onChange:N,value:h})}),(0,e.jsx)(l.Z.Item,{label:"\u884C\u95F4\u8DDD",children:(0,e.jsx)(s.Z,{min:1,max:10,step:1,onChange:X,value:C})})]})})]}),(0,e.jsx)("div",{style:{borderTop:"1px solid rgba(0,0,0,.1)",width:"100%",margin:"20px 0"}}),(0,e.jsx)(R.FormRender,{gridProps:{minColumns:p,maxColumns:x,columnGap:h,rowGap:C},layoutProps:{layout:_,size:m,gridColumnGap:i,labelCol:d,wrapperCol:c},fields:[{type:"Input",name:"Input",title:"Input"},{type:"Select",name:"Select",title:"Select2"},{type:"Input",name:"Input2",title:"Input"},{type:"Select",name:"Select2",title:"Select2"}]}),(0,e.jsx)("code",{children:(0,e.jsx)("pre",{children:`<FormRender
   layoutProps={{
      layout: `.concat(_,`,
      size: `).concat(m,`,
      gridColumnGap:`).concat(i,`,
      labelCol:`).concat(d,`,
      wrapperCol:`).concat(c,`,
    }}
    gridProps={{
      minColumns:`).concat(p,`,
      maxColumns:`).concat(x,`,
      columnGap:`).concat(h,`,
      rowGap:`).concat(C,`,
   }}
    fields={[...]}
   />`)})})]})}},13300:function(B,r,n){n.r(r);var v=n(50959),a=n(14550),t=n(11527);r.default=function(){return(0,t.jsx)(t.Fragment,{children:(0,t.jsx)(a.FormRender,{gridProps:{maxColumns:1},layoutProps:{layout:"vertical"},fields:[{type:"Input",name:"Input",title:"Input",required:!0},{type:"Select",name:"Select",title:"Select2",required:!0},{type:"Input",name:"Input2",title:"Input",required:!0},{type:"Select",name:"Select2",title:"Select2",required:!0}],children:function(o){return(0,t.jsxs)(t.Fragment,{children:[o,(0,t.jsx)(a.FormRender.FormButtonGroup,{children:(0,t.jsx)(a.FormRender.Submit,{onSubmit:console,children:"\u63D0\u4EA4"})})]})}})})}}}]);
